# Generated by Django 2.2.4 on 2021-12-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='frequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn_a_m_e', models.CharField(max_length=149)),
                ('fe_mail', models.CharField(max_length=149)),
                ('to_e_mail', models.CharField(max_length=149)),
                ('stz', models.CharField(max_length=149)),
            ],
        ),
        migrations.CreateModel(
            name='friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.CharField(max_length=149)),
                ('frnd_e', models.CharField(max_length=149)),
                ('frnd_n', models.CharField(max_length=149)),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_a_m_e', models.CharField(max_length=149)),
                ('e_mail', models.CharField(max_length=149)),
                ('msg', models.CharField(max_length=149)),
                ('picture', models.CharField(max_length=149)),
            ],
        ),
        migrations.CreateModel(
            name='usertab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_a_m_e', models.CharField(max_length=149)),
                ('e_mail', models.CharField(max_length=149)),
                ('pass_word', models.CharField(max_length=149)),
                ('phone', models.CharField(max_length=149)),
                ('gender', models.CharField(max_length=149)),
                ('picture', models.CharField(max_length=149)),
            ],
        ),
    ]
