# Generated by Django 3.1.3 on 2022-01-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_posts_stz'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='stz2',
            field=models.CharField(default=1, max_length=149),
            preserve_default=False,
        ),
    ]
